In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('data/BOLSAFAMILIA/visdata3-download-11-05-2025 133427.csv', encoding='latin1')

In [4]:
df

,Código,Unidade Territorial,UF,Referência,Total de Benefícios Básicos,Total de Benefícios Variáveis,Total de Benefícios Variáveis vinculados ao Jovem (BVJ),Total de Benefícios Variáveis vinculados à Nutriz (BVN),Total de Benefícios Variáveis vinculados à Gestante (BVG),Total de Benefícios para Superação da Extrema Pobreza (BSP)
0,150010,ABAETETUBA,PA,2008,12404,22889,3497.0,NaN,NaN,NaN
1,150010,ABAETETUBA,PA,2016,21586,30243,6229.0,421.0,636.0,16381.0
2,150010,ABAETETUBA,PA,2015,19325,27160,6322.0,236.0,467.0,15289.0
3,150010,ABAETETUBA,PA,2014,20707,29541,7339.0,310.0,534.0,16769.0
4,150010,ABAETETUBA,PA,2012,20719,31253,7311.0,145.0,527.0,11537.0
...,...,...,...,...,...,...,...,...,...,...
2577,150840,XINGUARA,PA,2016,3166,6766,943.0,136.0,136.0,1358.0
2578,150840,XINGUARA,PA,2021,3600,5691,980.0,119.0,44.0,1782.0
2579,150840,XINGUARA,PA,2006,1607,5262,NaN,NaN,NaN,NaN
2580,150840,XINGUARA,PA,2004,710,2585,NaN,NaN,NaN,NaN
2581,150840,XINGUARA,PA,2014,3454,6673,858.0,92.0,31.0,1378.0